services:
  passboltdb:
    image: mariadb:10.11
    restart: unless-stopped
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_DATABASE: "passbolt"
      MYSQL_USER: "passbolt"
      MYSQL_PASSWORD: "P4ssb0lt"
    volumes:
      - database_volume:/var/lib/mysql
    networks:
      - web

  passbolt:
    image: passbolt/passbolt:latest-ce
    #Alternatively you can use rootless:
    #image: passbolt/passbolt:latest-ce-non-root
    restart: unless-stopped
    depends_on:
      - passboltdb
    environment:
      APP_FULL_BASE_URL: https://pm.adrien-thibault.de
      DATASOURCES_DEFAULT_HOST: "passboltdb"
      DATASOURCES_DEFAULT_USERNAME: "passbolt"
      DATASOURCES_DEFAULT_PASSWORD: "P4ssb0lt"
      DATASOURCES_DEFAULT_DATABASE: "passbolt"
    volumes:
      - gpg_volume:/etc/passbolt/gpg
      - jwt_volume:/etc/passbolt/jwt
    command:
      [
        "/usr/bin/wait-for.sh",
        "-t",
        "0",
        "passboltdb:3306",
        "--",
        "/docker-entrypoint.sh",
      ]
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.password_manager.rule=Host(`pm.adrien-thibault.de`)"
      - "traefik.http.routers.password_manager.entrypoints=websecure"
      - "traefik.http.routers.password_manager.tls=true"
      - "traefik.http.routers.password_manager.tls.certresolver=production"
      - "traefik.http.services.password_manager.loadbalancer.server.port=80"
    networks:
      - web

networks:
  web:
    external: true

volumes:
  database_volume:
  gpg_volume:
  jwt_volume:
