version: "3"
services:
  watchtower:
    image: containrrr/watchtower
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - REPO_USER=user
      - REPO_PASS=password
      - WATCHTOWER_CLEANUP=true
    command: --interval 120