services:
  wordpress-app:
    image: wordpress
    restart: always
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: wordpress-db
      WORDPRESS_DB_USER: USERNAME
      WORDPRESS_DB_PASSWORD: PASSWORD
      WORDPRESS_DB_NAME: exampledb
    volumes:
      - wordpress:/var/www/html

  wordpress-db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: exampledb
      MYSQL_USER: USERNAME
      MYSQL_PASSWORD: PASSWORD
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - wordpress-db:/var/lib/mysql

volumes:
  wordpress:
  wordpress-db: